export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SELECT_CHAT = 'SELECT_CHAT';
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_ALL_CHATS = "GET_ALL_CHATS";
export const WRITE_NEW_PROFILE = "WRITE_NEW_PROFILE";