export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SELECT_CHAT = 'SELECT_CHAT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CURRENT_USER_ERROR = "CURRENT_USER_ERROR";
export const GET_USER_PROFILE = "GET_USER_PROFILE";

export const CREATE_CHAT = "CREATE_CHAT";
export const GET_ALL_CHATS = "GET_ALL_CHATS";
export const CREATE_PROFILE = "CREATE_PROFILE";